### ISSUE TITLE
Zotero Fails to Recognize Available Updates for the Plugin

### ISSUE THREAD

**Issue by themetalleg** [themetalleg/greatify#9]
I am experiencing an issue with the update notification system for my Zotero plugin. Despite creating and publishing new releases on GitHub, Zotero doesn't seem to recognize that an update is available. This remains the case even when users manually trigger the "Check for Updates" option within Zotero.

I have followed the necessary steps for releasing new versions, including updating version numbers, creating a new release on GitHub, uploading the updated .xpi file, and modifying the update.json and update.rdf files to point to the new release. However, Zotero still doesn't seem to identify these new releases as available updates.

Could you please review the setup for my recent releases and provide some insight into what I may be doing incorrectly? I want to ensure that users are notified of and able to download updates as soon as they are available.

I appreciate any assistance or guidance you can provide.

**Comment by northword** [comment]
Your latest release does not contain the xpi file

**Comment by themetalleg** [comment]
ok, that was now a coincidence. with all trying and testing I forgot it in the last one (added it now).
but it never worked also before with new releases.

**Comment by northword** [comment]
try https://github.com/windingwind/zotero-plugin-template/commit/3bd5b1137d2fb01d2dbc4d40d48dc80988dd7fce

or use json instead of rdf: https://github.com/northword/zotero-format-metadata/blob/dd11217958f30744f29d4406b79fbe75dc66caca/package.json#LL12C112-L12C112

**Comment by northword** [comment]
I'm confused about some values in your update.rdf, package.json, and update.json files that don't match. In addition, I noticed that you don't always commit all three files at the same time, and you deleted update-template.rdf and update-template.json? Do you manually update these files and create the release manually each time?

**Comment by themetalleg** [comment]
Omg, yes, I was also so confused... tried everything with the versions here and there and had also some settings from the zotero-template left. Now I understood the code much better and I finally had my addon auto-updated in Zotero. Thank you very much!
